name: Compile Kivy APK with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      # Executa o contêiner sob o usuário padrão do Kivy (evita o bloqueio de root)
      options: --user 1000:1000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fix Directory Permissions for Container
        run: |
          git config --global --add safe.directory /__w/nexusapp/nexusapp || true

      - name: Compile APK with Buildozer (Dockerized)
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
